language: java
env:
  global:
  # SONATYPE_USERNAME
  - secure: "YHml7a5G3Ytjcw5hY5sXB3Ab+WOwKSpXIjrotwUsdk+NtqpngROK8KNK5KYg/qzxS1oCLcWGu+wmk4yCbGOByR69/AuC7yk2yrNEYqFjekpVhLXtZsKNmrRaV2XH7blqKDtr0QPkwOMu6t5y6oI6Bbes7j8eVT7+wd+WfP17lt83cCBAwn3zcjttwNT60zZhg1OM4Hpua2IaHYT56XzhBjwibougNJi5+2bhR2Cwe5c2MESsS/8vyiNdhMkrV8qsgwdsVQCNkGbqjmonzrOq+yGX/surdwhypM0O1JyPU6o3oJLgPTNC2TPJBCowayoAZ6QUe9BYQbn1sMF+bPwMHSRY420k0q4KfqEn1uiUQGD4sMvZZG+ZibvN/R04ZPLz9N2ajH6yK4u9zXRVL2hePtpAVcUb5c0t6WPwaWPbFZWH0Ekm24VKz/8buud1nxE+WgpmfqA3qFfCqePlqMyli/meY/Fr7s5M7jEK3Bv8FfRfXatMdeR6Fl0S73dD4ybwWln79PPDvsjMFHl/4+DANZcnaAaINxfTcWS8YitJxwocOLPTTmlzIYnd4MrbShXzy53sse9PPlOtcom9aSYtrMd+RU4RDEfPbj8bQQyFUSNu+v7WFfqi8qV2auROke3zYNEyt52K35A7mVmPEnIzYGbPBerw93M5dyaDh12cHt4="
  # SONATYPE_PASSWORD
  - secure: "l1UKf07Wp1brmd9hFHpEM9I6LvL7pqJbRHYstlJKt1TnLitsLMQspGd4ASTJSBcsVDCXwirDPQKfun4H09oPGRATLg4v6aOokgO75QiGFZVOQ9lKsOgToUz2zmujaiCS/h/OpJOQeW5Ib7qI8D7Yxt9nL56F/u2kRT+i2ziNTNgK1Dx/pLvq99f9BkTwk1UDtbkghhCPeANwU4ZxoeU8kOK/p3pOjI2s9/En3BfJDe/RNZyG39N2sCGv7DsnDtY8hJoAofFGsuqW5tzvtGws4bVDXvlVpCfg1o5TrWUZ/KMnUfu/zCIeRiEvbEVHYEgSDw3hmz5meW1/BUCjbITwSWD+LYzBN0+6nt8wL/DLxNvMO8j43h5Da9ZIPEDqH/EMHrDclb8q0KQLUHORTdN+ZS//fUkFI6sQptUm/9eFKMPpSoydKufkK1Bndv8nTH7uh+wdevU+F9StL0v216g4f4K3h5AfuSttxPeo5IgiFVgh2Sd1JvoT25eYxewJfMJoB+UD+dV+FMwU3XWKg9b3YcgsP9BA/xvqmOKCSsboHnLVCQD6JVeF/mQNeCcZGvMHngycKu72eHEOkFV6r0nlRWbxzckroZFcP3YZCZCpzlN+WuTaiLX+r+klHL2sVEGnFKhcD6198wdNkxg7RIkzxBaYpMkkXxx3K2ITbVBri00="
  # GPG_KEYNAME
  - secure: "WDInp9WedYj/WR5En2myXyMnDFeJsJZKp57zuDpR/b5RNol/HtdVT6x4MNFAlQIh5ujSwIPQAj6w/6XxXyydm1H1nH2KeO8CK9Zvbr/H43VV4ctvr81Pm9U1D5OKFnRtEylK8vXh7S7jXiiEL4j470LQ0t2d1aK97NOOYNxT66FAqbONywCXCNPqocG4gN+IzYCwQqv/jzpoJe3by/oDrNC1YOwwlXDO6h3NeGpAFP2zB94562/YlJxz7rePZL7IWJQI7gkb3tOoeoRJlyZBgGL47rMltbJS3rcKlSOJttb76dcMRpsUJwp63C+n7GApRltkb0Q41XNyvon2z6UevW3VWhrIjl796ZaeGhb5ccsJWTS3s8IFtC2A0WnJdC/olWhg0d/BCAOeky8r79EmJGzfe5rVKNksD0JOzbTV/7Dxt7IM9+hhYm+jVLHQtufV7YRRw9MdWoMjlFnrRNs6mGcswOjEGr5OsdHUSvVY2p79hoEHWfTJ66WOgPW2hREI8o7ctwVrX5V+GNozUOrbVsH6t7oz7qhjpKwu5QpJhorTpzrefcyMAsQaSntBksSHwxTA261lx0epVVNU/UXn8OiiYkQhNtkvXbSgnDl4pnRJkGPNjb1iYNfMKKdM9CAgSgNC15sO1CQZyPC+1HpyOK1HCD1cmRhJH/4R/zjfkN0="
  # GPG_PASSPHRASE
  - secure: "zEPaJeR61/pq2wqsaIUvmDXJLcE6mFo3sS0f98CHcsrzqAwcorwGzauozSY0Dhz/Ac3mTpgsrKadtQ6Gi8jJMZdB2VDfoAE3j0Sd92SxXY7XEaQvnLuPN7uEjCKQg16woAwMnaYfIhoZUZy3vVrk9IXxWuXqPFbpX1/L4yr3BhIdP/5yydbCt+NSsXZ//tHS7Th2kDcb8rQWfrY172E7JHkfPudieABLeJS6gJkgtt1SwIxfx8nLw45DP3d1t/hxnj6hiDC8SXjvkpJ7aV5Sg9zaxTRabBu8m1bb/zOu9IdMUlKzSSu0Ji1OUunYodat0yy2lXU/JQc7oK5vzwrJL6aL9XMNfU53fV1i/S13otiP3o3qZYpM/ilkgcVdpZ7xpLaN4LvXiOxK9jWu+xeH9a0hDuZykwIxzsfV/ooccWBVQuWzscmGQQuCfIwX8v0zbk4wLvBIxDz4gSfQCN9Vi1+cfeNbXTFwhS6zdLweJBW45DC2vKi/LypnQYwjog//sHvNmHZzDluZeSYbN6S/fTpphmUXpk4GqWcby4hValkCiBpt6G2ZoxbXIojMKW6q0igaQMuwGChGwZJsSZyfXUmcSOwuwLRHPahtTwu6nEPFYUgBlaHd49CrcW09CBPHfJWkkM3athXdmXKgsl207UiEfWCt8sirJgx5G1ySsqY="
cache:
  directories:
    - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv
  -in $TRAVIS_BUILD_DIR/deploy/gpg.tar.gz.enc -out $TRAVIS_BUILD_DIR/deploy/gpg.tar.gz -d
- tar xzvf $TRAVIS_BUILD_DIR/deploy/gpg.tar.gz -C $TRAVIS_BUILD_DIR/deploy
- cp $TRAVIS_BUILD_DIR/deploy/.travis.settings.xml $HOME/.m2/settings.xml
install: mvn dependency:resolve
script:
- mvn install deploy -B -V -P deployment
deploy:
  provider: script
  script:
  - mvn deploy -P deployment
  skip_cleanup: true
  on:
    tags: true
